spring:
  application:
    name: 08-Config-Client-2
    
  config:
    import: optional:configserver:http://localhost:9091
    
management:
  endpoints:
    web:
      exposure:
        include: refresh    
    
server:
  port: 8082