spring:
  application:
    name: 05-MS-1-API-Gateway
    
  cloud:
    gateway:
      routes:
      - id: api-1
        uri: lb://03-MS-1-WelcomeMicroService
        predicates:
        - Path=/welcome
      - id: api-2
        uri: lb://04-MS-1-GreetMicroService
        predicates:
        - Path=/greet
        
server:
  port: 3333 