spring:
  application:
    name: 04-MS-1-GreetMicroService
  boot:
    admin:
      client:
        url: http://localhost:1111/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
server:
  port: 9091